### ISSUE TITLE
Basically you built a FreeCAD macro debugger..?

### ISSUE THREAD

**Issue by luzpaz** [dprojects/scanObjects#1]
?

**Comment by dprojects** [comment]
It wasn't intentional. I did not know what data can be obtained for dimensions. I didn't want to type the commands at the python console all day to find out e.g. if it is possible to get the color for the edge somehow, or edge dimension or other useful property. Debugger and module viewer came out by accident ;-) I didn't even think it could be done that easily ;-)

**Comment by luzpaz** [comment]
Related to https://github.com/FreeCAD/FreeCAD/issues/5540  
Would you be open to adding this macro to the official FreeCAD-macros repo so others may be interested in collaborating (if you're interested in collaborating?)

**Comment by dprojects** [comment]
I want to keep my GitHub account private, without other folks collaborating. This is not because I don't like others (funny team spirit ;-) LOL) but this is because I don't want to manage dependencies here. I code for fun here, and want to leave it here like this. 

However, all my code publicly available is under MIT license so it can be added everywhere, anyone can make forks, split it and manage it's own version. So, there is no problem for me to collaborate elsewhere, or submit this elsewhere as a base or added value. I don't know about collaborating to FreeCAD repository. I saw that macros need special methods like "do_main" or something like that. So to put there I would need make changes? I have no idea how to do it in fact.

**Comment by luzpaz** [comment]
Yea, there are some coding standards that are asked of macro writers when adding to the repository.  
If you have your boundaries around that, that's cool. Thanks for your efforts thus far. I won't bug you about such things in the future.

**Comment by dprojects** [comment]
All my tools are at: https://wiki.freecadweb.org/Macros_recipes the scanObjects is in "Code and Scripting" section linked. I remember I was looking there for such inspection tool before I made it. So this should be available for all FreeCAD users that need it like me before. 

Regarding sending code to anywhere "by me" is problematic matter, this is not because of do_main() but:
- If I submit I need to make fixes and updates, twice, or even in more places. 
- I would have to maintain it there and take care about dependencies and add-on manager version changes.
- Also I am not sure if the current state is good to freeze it somewhere. Anyone can decide on your own by making fork.
- I make updates sometimes very often. So this multiple the job of testing, coding, preparing special version or each split or add-on manager or repository. If someone make fork he maintain it and decide if he want add new changes or not. That's people's choice now.

You don't bug me, it is fine. I agree it would be better to have it all at FreeCAD. So, I still thinking about your needs, and FreeCAD users, what to do with it. 

Maybe someday I find the exact way or the way find me ;-)
